import AsyncStorage from "@react-native-async-storage/async-storage";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useEffect, useState } from "react";
import { startOAuthLogin } from "@/constants/oauth";
import { ScreenContainer } from "@/components/screen-container";
import { WinkkitBadge, WinkkitButton, WinkkitCard } from "@/components/winkkit";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAuth } from "@/hooks/use-auth";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type RequestedRole = "user" | "shopkeeper" | "delivery";
const ROLE_KEY = "winkkit_requested_role";

export default function AccountScreen() {
  const colors = useColors();
  const router = useRouter();
  const { user, loading, isAuthenticated, logout, refresh } = useAuth();
  const [requestedRole, setRequestedRole] = useState<RequestedRole>("user");
  const [roleSaving, setRoleSaving] = useState(false);
  const [notice, setNotice] = useState("");
  const profile = trpc.account.profile.useQuery(undefined, { enabled: isAuthenticated });
  const shop = trpc.shopkeeper.shop.useQuery(undefined, { enabled: isAuthenticated && profile.data?.role === "shopkeeper" });
  const requestRole = trpc.auth.requestRole.useMutation();
  const createShop = trpc.shopkeeper.createShop.useMutation({ onSuccess: () => { setNotice("Shop setup submitted. Your account is awaiting approval."); shop.refetch(); } });
  const [shopForm, setShopForm] = useState({ name: "", address: "", description: "", openingTime: "09:00", closingTime: "21:00" });

  useEffect(() => { AsyncStorage.getItem(ROLE_KEY).then((value) => { if (value === "shopkeeper" || value === "delivery" || value === "user") setRequestedRole(value); }); }, []);

  const selectRole = async (role: RequestedRole) => { setRequestedRole(role); await AsyncStorage.setItem(ROLE_KEY, role); setNotice(""); };
  const signIn = async () => { setNotice(""); try { const result = await startOAuthLogin(); if (result === null && typeof window === "undefined") setNotice("Opening secure sign-in… If nothing opens, install the latest Winkkit APK and try again."); } catch (error) { setNotice(error instanceof Error ? error.message : "We could not open secure sign-in. Please try again."); } };
  const submitRole = async () => {
    setRoleSaving(true); setNotice("");
    try {
      await requestRole.mutateAsync({ role: requestedRole });
      await refresh();
      setNotice(requestedRole === "user" ? "Customer account ready." : `${requestedRole === "shopkeeper" ? "Shopkeeper" : "Delivery partner"} application submitted for approval.`);
    } catch { setNotice("We could not save your account type. Please try again."); } finally { setRoleSaving(false); }
  };
  const submitShop = async () => {
    setNotice("");
    try { await createShop.mutateAsync(shopForm); } catch { setNotice("We could not save your shop details. Please check the required fields."); }
  };

  if (loading) return <ScreenContainer><View style={styles.loading}><ActivityIndicator color={colors.primary} /></View></ScreenContainer>;
  if (!isAuthenticated) return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content}><View style={styles.intro}><View style={[styles.mark, { backgroundColor: colors.primary }]}><Text style={styles.markText}>W</Text></View><Text style={[styles.title, { color: colors.foreground }]}>Sign in to Winkkit</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Use one secure account. Your backend role determines which workspace you can access.</Text></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>I am joining as</Text><View style={styles.roleList}><RoleOption role="user" label="Customer" description="Browse local shops and place orders" selected={requestedRole === "user"} onPress={() => selectRole("user")} /><RoleOption role="shopkeeper" label="Shopkeeper" description="Manage your shop, products, and orders" selected={requestedRole === "shopkeeper"} onPress={() => selectRole("shopkeeper")} /><RoleOption role="delivery" label="Delivery partner" description="Accept deliveries and track earnings" selected={requestedRole === "delivery"} onPress={() => selectRole("delivery")} /></View><WinkkitButton label="Sign in or create account" onPress={signIn} />{notice ? <Text style={[styles.notice, { color: colors.primary }]}>{notice}</Text> : null}<Text style={[styles.helper, { color: colors.muted }]}>Winkkit uses secure OAuth. No password is stored in this app.</Text></ScrollView></ScreenContainer>;

  const effectiveUser = profile.data ?? user;
  const role: string = effectiveUser?.role ?? "user";
  const status: string = effectiveUser?.status ?? "active";
  if (role === "user" && requestedRole !== "user") return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: colors.foreground }]}>Choose your Winkkit workspace</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Your current account is authenticated. Confirm the backend role you want to request.</Text><View style={styles.roleList}><RoleOption role="shopkeeper" label="Shopkeeper" description="Requires approval before accepting orders" selected={requestedRole === "shopkeeper"} onPress={() => selectRole("shopkeeper")} /><RoleOption role="delivery" label="Delivery partner" description="Requires approval before accepting jobs" selected={requestedRole === "delivery"} onPress={() => selectRole("delivery")} /></View>{notice ? <Text style={[styles.notice, { color: colors.primary }]}>{notice}</Text> : null}<WinkkitButton label={roleSaving ? "Saving account type…" : "Continue"} disabled={roleSaving} onPress={submitRole} /></ScrollView></ScreenContainer>;
  if (role === "shopkeeper" && !shop.data) return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: colors.foreground }]}>Set up your shop</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Complete the first onboarding step. You can add products after approval.</Text><Field label="Shop name *" value={shopForm.name} onChangeText={(value) => setShopForm((current) => ({ ...current, name: value }))} placeholder="Fresh Basket Market" /><Field label="Shop address *" value={shopForm.address} onChangeText={(value) => setShopForm((current) => ({ ...current, address: value }))} placeholder="Street, area, city" /><Field label="Description" value={shopForm.description} onChangeText={(value) => setShopForm((current) => ({ ...current, description: value }))} placeholder="What do you sell?" multiline /><View style={styles.inline}><Field label="Opens" value={shopForm.openingTime} onChangeText={(value) => setShopForm((current) => ({ ...current, openingTime: value }))} placeholder="09:00" /><Field label="Closes" value={shopForm.closingTime} onChangeText={(value) => setShopForm((current) => ({ ...current, closingTime: value }))} placeholder="21:00" /></View>{notice ? <Text style={[styles.notice, { color: colors.primary }]}>{notice}</Text> : null}<WinkkitButton label={createShop.isPending ? "Submitting shop…" : "Submit shop for approval"} disabled={createShop.isPending || !shopForm.name.trim() || !shopForm.address.trim()} onPress={submitShop} /></ScrollView></ScreenContainer>;

  return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: colors.foreground }]}>Account</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Your access is controlled by the backend role and account status.</Text><WinkkitCard style={styles.profile}><View style={[styles.avatar, { backgroundColor: `${colors.primary}12` }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{(user?.name || user?.email || "W").slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileText}><Text style={[styles.name, { color: colors.foreground }]}>{user?.name || "Winkkit account"}</Text><Text style={[styles.email, { color: colors.muted }]}>{user?.email || "Verified account"}</Text></View><WinkkitBadge label={role === "admin" ? "Admin" : role === "shopkeeper" ? "Shopkeeper" : role === "delivery" ? "Delivery" : "Customer"} tone="aqua" /></WinkkitCard>{status === "pending" ? <WinkkitCard style={styles.pending}><IconSymbol name="clock.fill" size={20} color={colors.warning} /><Text style={[styles.pendingText, { color: colors.foreground }]}>Your {role === "shopkeeper" ? "shopkeeper" : "delivery partner"} account is awaiting approval. You can return here to check status.</Text></WinkkitCard> : null}{status === "active" && (role === "shopkeeper" || role === "delivery" || role === "admin") ? <WinkkitButton label="Open operations workspace" onPress={() => router.push("/operations")} /> : null}<Pressable onPress={logout} style={[styles.logout, { borderColor: colors.border }]}><IconSymbol name="logout" size={18} color={colors.error} /><Text style={[styles.logoutText, { color: colors.error }]}>Log out securely</Text></Pressable></ScrollView></ScreenContainer>;
}

function RoleOption({ role, label, description, selected, onPress }: { role: RequestedRole; label: string; description: string; selected: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={[styles.roleOption, { borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? `${colors.primary}10` : colors.surface }]}><View style={[styles.roleDot, { backgroundColor: selected ? colors.primary : colors.border }]}>{selected ? <Text style={styles.check}>✓</Text> : null}</View><View style={styles.roleText}><Text style={[styles.roleLabel, { color: colors.foreground }]}>{label}</Text><Text style={[styles.roleDescription, { color: colors.muted }]}>{description}</Text></View></Pressable>; }
function Field({ label, value, onChangeText, placeholder, multiline = false }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; multiline?: boolean }) { const colors = useColors(); return <View style={styles.field}><Text style={[styles.fieldLabel, { color: colors.foreground }]}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} multiline={multiline} style={[styles.input, multiline && styles.multiline, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.foreground }]} /></View>; }

const styles: any = StyleSheet.create({ content: { paddingBottom: 34 }, loading: { paddingVertical: 60, alignItems: "center" }, intro: { alignItems: "center", padding: 12 }, mark: { width: 64, height: 64, borderRadius: 22, alignItems: "center", justifyContent: "center", marginBottom: 18 }, markText: { color: "#FFFFFF", fontSize: 30, fontWeight: "800" }, title: { fontSize: 28, lineHeight: 34, fontWeight: "800", marginBottom: 7 }, subtitle: { fontSize: 14, lineHeight: 21, marginBottom: 24 }, sectionTitle: { fontSize: 16, fontWeight: "800", marginBottom: 10 }, roleList: { gap: 10, marginBottom: 18 }, roleOption: { minHeight: 76, borderWidth: 1, borderRadius: 16, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, roleDot: { width: 25, height: 25, borderRadius: 13, alignItems: "center", justifyContent: "center" }, check: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, roleText: { flex: 1 }, roleLabel: { fontSize: 15, fontWeight: "800" }, roleDescription: { fontSize: 12, lineHeight: 17, marginTop: 3 }, helper: { textAlign: "center", fontSize: 12, lineHeight: 17, marginTop: 14 }, notice: { fontSize: 13, lineHeight: 19, marginBottom: 14 }, profile: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 18 }, avatar: { width: 50, height: 50, borderRadius: 16, alignItems: "center", justifyContent: "center" }, avatarText: { fontSize: 22, fontWeight: "800" }, profileText: { flex: 1 }, name: { fontSize: 16, fontWeight: "800" }, email: { fontSize: 13, marginTop: 4 }, pending: { flexDirection: "row", gap: 10, alignItems: "flex-start", marginBottom: 18 }, pendingText: { flex: 1, fontSize: 13, lineHeight: 19 }, logout: { minHeight: 48, borderWidth: 1, borderRadius: 14, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, marginTop: 18 }, logoutText: { fontSize: 14, fontWeight: "800" }, field: { marginBottom: 15, flex: 1 }, fieldLabel: { fontSize: 13, fontWeight: "700", marginBottom: 7 }, input: { minHeight: 50, borderWidth: 1, borderRadius: 14, paddingHorizontal: 13, paddingVertical: 12, fontSize: 14 }, multiline: { minHeight: 86, textAlignVertical: "top" }, inline: { flexDirection: "row", gap: 10 } });
