import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { startOAuthLogin } from "@/constants/oauth";
import { ScreenContainer } from "@/components/screen-container";
import { WinkkitButton, WinkkitCard } from "@/components/winkkit";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAuth } from "@/hooks/use-auth";
import { useColors } from "@/hooks/use-colors";

export default function AccountScreen() {
  const colors = useColors();
  const { user, loading, isAuthenticated, logout } = useAuth();
  if (loading) return <ScreenContainer><View style={styles.loading}><ActivityIndicator color={colors.primary} /></View></ScreenContainer>;
  if (!isAuthenticated) return <ScreenContainer className="p-5"><View style={styles.intro}><View style={[styles.mark, { backgroundColor: colors.primary }]}><Text style={styles.markText}>W</Text></View><Text style={[styles.title, { color: colors.foreground }]}>Welcome to Winkkit</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Sign in to save addresses, place orders, and receive live delivery updates.</Text><WinkkitButton label="Sign in securely" onPress={() => startOAuthLogin()} /></View></ScreenContainer>;
  return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: colors.foreground }]}>Account</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Manage your Winkkit profile and delivery preferences.</Text><WinkkitCard style={styles.profile}><View style={[styles.avatar, { backgroundColor: `${colors.primary}12` }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{(user?.name || user?.email || "W").slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileText}><Text style={[styles.name, { color: colors.foreground }]}>{user?.name || "Winkkit customer"}</Text><Text style={[styles.email, { color: colors.muted }]}>{user?.email || "Verified account"}</Text></View></WinkkitCard><View style={styles.menu}><MenuRow icon="location.fill" label="Saved addresses" /><MenuRow icon="bell" label="Notifications" /><MenuRow icon="settings" label="Settings" /><MenuRow icon="shield" label="Privacy and security" /></View><Pressable onPress={logout} style={[styles.logout, { borderColor: colors.border }]}><IconSymbol name="logout" size={18} color={colors.error} /><Text style={[styles.logoutText, { color: colors.error }]}>Log out</Text></Pressable></ScrollView></ScreenContainer>;
}

function MenuRow({ icon, label }: { icon: "location.fill" | "bell" | "settings" | "shield"; label: string }) { const colors = useColors(); return <Pressable style={styles.menuRow}><IconSymbol name={icon} size={20} color={colors.primary} /><Text style={[styles.menuLabel, { color: colors.foreground }]}>{label}</Text><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>; }

const styles: any = StyleSheet.create({ content: { paddingBottom: 32 }, intro: { flex: 1, justifyContent: "center", alignItems: "center", padding: 26 }, mark: { width: 70, height: 70, borderRadius: 24, alignItems: "center", justifyContent: "center", marginBottom: 22 }, markText: { color: "#FFFFFF", fontSize: 34, fontWeight: "800" }, title: { fontSize: 28, fontWeight: "800", textAlign: "center" }, subtitle: { fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 8, marginBottom: 24 }, profile: { flexDirection: "row", alignItems: "center", gap: 13, marginTop: 22 }, avatar: { width: 52, height: 52, borderRadius: 17, alignItems: "center", justifyContent: "center" }, avatarText: { fontSize: 22, fontWeight: "800" }, profileText: { flex: 1 }, name: { fontSize: 16, fontWeight: "800" }, email: { fontSize: 13, marginTop: 4 }, menu: { marginTop: 24, gap: 6 }, menuRow: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: 13 }, menuLabel: { flex: 1, fontSize: 15, fontWeight: "600" }, logout: { borderWidth: 1, minHeight: 48, borderRadius: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 28 }, logoutText: { fontSize: 14, fontWeight: "800" }, loading: { paddingVertical: 60, alignItems: "center" } });
