import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { WinkkitButton, WinkkitCard, WinkkitEmptyState } from "@/components/winkkit";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useCart } from "@/lib/cart";

export default function CartScreen() {
  const colors = useColors();
  const router = useRouter();
  const { lines, subtotalCents, syncing, add, decrement, clear } = useCart();
  if (!lines.length) return <ScreenContainer><WinkkitEmptyState title="Your cart is empty" message="Browse approved local shops and add products to begin an order." action="Find a shop" onAction={() => router.push("/search")} /></ScreenContainer>;
  return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={[styles.title, { color: colors.foreground }]}>Your cart</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{lines[0].shopName}</Text><WinkkitCard style={styles.syncCard}><IconSymbol name="cloud" size={18} color={colors.primary} /><Text style={[styles.syncText, { color: colors.foreground }]}>{syncing ? "Saving your cart online…" : "Your cart is saved online when signed in"}</Text></WinkkitCard><View style={styles.lines}>{lines.map((line) => <WinkkitCard key={line.id} style={styles.line}><View style={styles.lineInfo}><Text style={[styles.name, { color: colors.foreground }]} numberOfLines={2}>{line.name}</Text><Text style={[styles.price, { color: colors.muted }]}>₹{(line.priceCents / 100).toFixed(2)} each</Text></View><View style={styles.controls}><Pressable onPress={() => decrement(line.id)} style={[styles.control, { borderColor: colors.border }]}><IconSymbol name="minus" size={16} color={colors.foreground} /></Pressable><Text style={[styles.quantity, { color: colors.foreground }]}>{line.quantity}</Text><Pressable onPress={() => add(line)} style={[styles.control, { backgroundColor: colors.primary }]}><IconSymbol name="plus" size={16} color="#FFFFFF" /></Pressable></View></WinkkitCard>)}</View><View style={[styles.summary, { borderColor: colors.border }]}><View style={styles.summaryRow}><Text style={[styles.summaryLabel, { color: colors.muted }]}>Subtotal</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>₹{(subtotalCents / 100).toFixed(2)}</Text></View><View style={styles.summaryRow}><Text style={[styles.summaryLabel, { color: colors.muted }]}>Delivery and platform fees</Text><Text style={[styles.summaryValue, { color: colors.muted }]}>Calculated at checkout</Text></View><WinkkitButton label="Continue to checkout" onPress={() => router.push("/checkout")} /><Pressable onPress={clear} style={styles.clear}><Text style={[styles.clearText, { color: colors.error }]}>Clear cart</Text></Pressable></View></ScrollView></ScreenContainer>;
}

const styles: any = StyleSheet.create({ content: { paddingBottom: 32 }, title: { fontSize: 28, fontWeight: "800" }, subtitle: { fontSize: 14, marginTop: 6, marginBottom: 22 }, syncCard: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 14 }, syncText: { flex: 1, fontSize: 12, fontWeight: "700" }, lines: { gap: 11 }, line: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, lineInfo: { flex: 1, minWidth: 0 }, name: { fontSize: 15, fontWeight: "800", marginBottom: 6 }, price: { fontSize: 13 }, controls: { flexDirection: "row", alignItems: "center", gap: 10 }, control: { width: 32, height: 32, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" }, quantity: { fontSize: 15, fontWeight: "800", minWidth: 18, textAlign: "center" }, summary: { borderTopWidth: 1, marginTop: 26, paddingTop: 20, gap: 14 }, summaryRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, summaryLabel: { fontSize: 14, flex: 1 }, summaryValue: { fontSize: 14, fontWeight: "700", textAlign: "right" }, clear: { alignItems: "center", paddingVertical: 6 }, clearText: { fontSize: 13, fontWeight: "700" } });
